#cloud-config
hostname: terraform-vm
fqdn: terraform-vm.local

users:
  - name: ${vm_user}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo, docker
    shell: /bin/bash
    ssh-authorized-keys:
      - ${ssh_key}
    disable_root: false
    ssh_pwauth: false

package_update: true
package_upgrade: true
packages:
  - curl
  - htop

runcmd:
  - echo "Welcome to your Terraform provisioned VM!" | sudo tee /etc/motd